defaults: &defaults
  adapter:  mysql
  host:     localhost
  username: root
  password: 
  encoding: utf8

development:
  database: translator_development
  <<: *defaults

mysql_development:
  database: translator_development
  pool: 250
  timeout: 5000
  <<: *defaults

sqlite_development:
  adapter: sqlite3
  database: /Users/felixbellanger/Desktop/WIP/Faveod/VMs/squeeze64/vhosts/poeditor/db/locales_development.sqlite3
  pool: 5
  timeout: 5000